name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          start: npm run dev
          wait-on: http://localhost:5173/
          record: false
        env:
          CYPRESS_baseUrl: http://localhost:5173/
          CYPRESS_VIDEO: false